### ISSUE TITLE
Problem with appointments created from e-mails

### ISSUE THREAD

**Issue by 7weazel7** [iCalcreator/iCalcreator#89]
For example, if you create an appointment with an iPhone from an e-mail, the e-mail will be linked in the appointment. This URL cannot be processed then. You can't edit this field in the appointment either, you have to delete the appointment.

URL;VALUE=URI:message:%3C01020175ae0fa363-b7ebfe82-02d0-420a-a8d9-331e43f
 a1867-000000@eu-west-1.amazonses.com%3E

parse: URL validity error #2, 'message:%3C01020175ae0fa363-b7ebfe82-02d0-420a-a8d9-331e43fa1867-000000@eu-west-1.amazonses.com%3E'

![image](https://user-images.githubusercontent.com/67899424/101259118-38bb8e00-3727-11eb-85b2-8cb1e14bb83f.png)

**Comment by iCalcreator** [comment]
Looking into the issue

**Comment by iCalcreator** [comment]
Fixed in 2.29.30, please verify!

**Comment by 7weazel7** [comment]
Still have this problem :/

13.12.2020, 13:35:47 |              LOG_ERR | parse: URL validity error #2, 'message:%3C20160307195914.8558D20186@edu.school.de%3E'

BEGIN:VEVENT<CR><LF>CREATED:20160307T210232Z<CR><LF>DTEND;VALUE=DATE:20160421<CR><LF>DTSTAMP:20160307T210234Z<CR><LF>DTSTART;VALUE=DATE:20160420<CR><LF>LAST-MODIFIED:20160307T210232Z<CR><LF>LOCATION:Stutt<CR><LF>gart<CR><LF>SEQUENCE:0<CR><LF>SUMMARY:Test Mail<CR><LF>UID:24B3E02E-1E93-47D4-9E21-3336F0576E7C<CR><LF>URL;VALUE=URI:message:%3C20160307195914.8558D20186@edu.school.d<CR><LF> e%3E<CR><LF>END:VEVENT

**Comment by iCalcreator** [comment]
Very tricky to fix this but working on...

BUT rfc5545 say :
_Property parameter values that contain the COLON, SEMICOLON, or COMMA character separators MUST be specified as quoted-string text values._

**Comment by iCalcreator** [comment]
Try (tag) 2.29.30b

Who is the originator of the ical 'snippet'?
You should raise issues there, both for the URL parameter value and property value.

**Comment by iCalcreator** [comment]
Try (tag) 2.29.30b

Who is the originator of the ical 'snippet'?
You should raise issues there, both for the URL parameter value and property value.

**Comment by 7weazel7** [comment]
Sorry for the late reply. We were able to recreate this. This is definitely an Apple iCloud Calendar issue. Someone needs to pass this on to Apple.

**Comment by 7weazel7** [comment]
Hi, 

I think we have found the error. It is the function "setUrl". What does this function do exactly? For testing purposes, we have included a return. And there they are, the entries can be triggered.

`
 public function setUrl( $value = null, $params = [] )
    {
        return $value;
        static $PFCHARS1 = '%3C';
        ........................
        ....................
`

Here is the original event. I masked the sensitive stuff.

`
BEGIN:VEVENT
CREATED:20201211T151328Z
DESCRIPTION:Test Entry\nID: 809704
DTEND;TZID=Europe/Berlin:20210122T180000
DTSTAMP:20210202T164643Z
DTSTART;TZID=Europe/Berlin:20210122T080000
LAST-MODIFIED:20210202T164643Z
LOCATION:Sushistr.\, 56\, Berlin \, 88465
SEQUENCE:0
SUMMARY:Mahallo
UID:2FE9649C-6831-4712-8609-76CE18BE530A
URL;VALUE=URI:https://www.masked.de/account/subscription/delivery/8878/%3Fweek=2021-W03
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=CAES/gEI2TIaE
 gk25nXEIQFIQBFB0xIro9EjQCJuCgtEZXV0c2NobGFxcyxcUaEkJhZGVuLVfDvHJ0dGVtY
 mVyZyoIQmliZXJhY2gyGVN0ZWluaGF1c2VuIGFuIGRlciBSb3R0dW06BTg4NDE2UglBdXN0c
 mHDn2VaAjEyYgxyxyyxmHDn2UgMTIqDEF1c3RyYcOfZSAxMjIMQXVzdHJhw59lIDEyMh84O
 DQxNiBTdGVpbmhhdXNlbiBhbiBkZXIgUm90dHVtMgtEZXV0c2NobGFuZDg5QABaJwolEhIJN
 uZ1xCEBSEARQdMSK6PRI0AY2TIgg+6c5cCxwdjIAZADAQ==;X-APPLE-RADIUS=70.587362
 39271092;X-APPLE-REFERENCEFRAME=1;X-TITLE="Sushistr., 56, Berlin , 88465
 ":geo:52.008843,12.09448
END:VEVENT
`

**Comment by iCalcreator** [comment]
The URL parameter 'VALUE=URI' is not required, it is the property (default) type.
But try the new (tag) release 2.30.2!

**Comment by bumaas** [comment]
I have tried the current release 2.30.2, but get still an error:

URL validity error #2, ';VALUE=URI:message://%3C1714214488.13907.1453128266311.JavaMail.tomcat%40web-pdfe-f02%3E?c=1453128266&k=%7Cticket%5C%7C1797815930%5C%7C2016-07-20'

Do you have any idea, what is wrong?

BR Burkhard

**Comment by iCalcreator** [comment]
There are two errors in the URL value:

#1 the value is NOT urldecoded, required according the rfc5545 (->rfc3986)

#2 invalid value prefix '//'

These strings (to parse) works for me

'URL;VALUE="URI:message":1714214488.13907.1453128266311.JavaMail.tomcat@web-pdfe-f02?c=1453128266&k=|ticket\|1797815930\|2016-07-20'

'URL;VALUE=URI:message:1714214488.13907.1453128266311.JavaMail.tomcat@web-pdfe-f02?c=1453128266&k=|ticket\|1797815930\|2016-07-20'

**Comment by bumaas** [comment]
Thanks for your hints. Unfortunately I can't remember how these kind of entries was imported in my iCloud calender. So I will correct them.

**Comment by 7weazel7** [comment]
> The URL parameter 'VALUE=URI' is not required, it is the property (default) type.
> But try the new (tag) release 2.30.2!

Unfortunately, the problem still exists. Do you need more logs?

**Comment by iCalcreator** [comment]
Thanks, so 'message://' is a URI property value prefix, not a parameter-part, ok. 
Working on it now, prel. release in a few days.

**Comment by 7weazel7** [comment]
> Thanks, so 'message://' is a URI property value prefix, not a parameter-part, ok.
yes exactly right. Sorry if I had described this incorrectly

**Comment by iCalcreator** [comment]
To conclude : 
Fix the URL value prefix 'message://' (also 'http[s]://').
But what about the prefix 'message:' ?
Values should (must) be urldecoded, but I fix '<>@' urldecode (and the '<>' removal).

OK?

**Comment by 7weazel7** [comment]
@bumaas 

> To conclude :
> Fix the URL value prefix 'message://' (also 'http[s]://').
> But what about the prefix 'message:' ?
> Values should (must) be urldecoded, but I fix '<>@' urldecode (and the '<>' removal).
> 
> OK?

I'm sorry, but I don't quite understand. Excuse me.
As far as I could verify, Apple references with the prefix message:// an internal mail on the internal memory of the device (for example the iPhone)

@bumaas 
Do you have any idea what exactly is meant? Can I test something again?

**Comment by iCalcreator** [comment]
Yes, please test the new release 2.30.3!

**Comment by 7weazel7** [comment]
It works :) Thanks for your help!

**Comment by 7weazel7** [comment]
Me again. I don't know why, but sometimes the entries are inserted with prefix "message://" and sometimes with "message:". We couldn't see any behavior pattern yet.

Could you catch "message:" as well?

**Comment by iCalcreator** [comment]
Fix it during the weekend.

**Comment by iCalcreator** [comment]
Release 2.30.4
